ems/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('note.urls')),
    path('login' , login , name = 'login'),
    path('logout' , logout_view , name = 'logout'),
    path('ckeditor' , include('ckeditor_uploader.urls')),
    path('items' , include('items.urls')),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

note/urls.py
from django.urls import path
from .views import *

urlpatterns = [
		#未报账
		path('' , wbz_all , name = 'wbz_all'),
		path('wbz_dj' , wbz_dj , name = 'wbz_dj'),
		path('wbz_jsj' , wbz_jsj , name = 'wbz_jsj'),
		path('wbz_wl' , wbz_wl , name = 'wbz_wl'),
		#未报账图表
		path('wbz_tb' , wbz_tb , name = 'wbz_tb'),
		#已报账
		path('ybz_all' , ybz_all , name = 'ybz_all'),
		path('ybz_dj' , ybz_dj , name = 'ybz_dj'),
		path('ybz_wl' , ybz_wl , name = 'ybz_wl'),
		path('ybz_jsj' , ybz_jsj , name = 'ybz_jsj'),
		#已报账详细信息
		path('ybz_xx' , ybz_xx , name = 'ybz_xx'),
		#管理页面
		path('manage_wbz' , manage_wbz , name = 'manage_wbz'),
		path('manage_ybz' , manage_ybz , name = 'manage_ybz'),
		path('manage_sh' , manage_sh , name = 'manage_sh'),
		path('manage_lx' , manage_lx , name = 'manage_lx'),
		path('manage_xh' , manage_xh , name = 'manage_xh'),
		#修改记录
		path('edit_note' , edit_note , name = 'edit_note'),
		path('edit_sh' , edit_sh , name = 'edit_sh'),
		path('edit_lx' , edit_lx , name = 'edit_lx'),
		path('edit_xh' , edit_xh , name = 'edit_xh'),
		#修改密码
		path('manage_mm' , manage_mm , name = 'manage_mm'),
		#删除记录
		path('delete_note' , delete_note , name = 'delete_note'),
		#新增记录
		path('new_note' , new_note , name = 'new_note'),
		path('new_customer' , new_customer , name = 'new_customer'),
		path('new_unit_type' , new_unit_type , name = 'new_unit_type'),
		path('new_unit_model' , new_unit_model , name = 'new_unit_model'),
		#x新增记录ajax
		path('ajax_get_unit_types' , ajax_get_unit_types , name = 'ajax_get_unit_types'),
		path('ajax_get_unit_models' , ajax_get_unit_models , name = 'ajax_get_unit_models'),
		#报账
		path('bz' , bz , name = 'bz'),
		#打印页面
		path('dy' , dy , name = 'dy'),
		#下载页面
		path('download' , download , name = 'download'),
		#报账界面ajax获取notes
		path('ajax_get_notes' , ajax_get_notes , name = 'ajax_get_notes'),
		#获取记录详细信息
		path('ajax_get_notes_detail' , ajax_get_notes_detail , name = 'ajax_get_notes_detail'),
]

note/models/customers.py
from django.db import models
from django.contrib.auth.models import Group

#售后单位
class Customer(models.Model):
    title = models.CharField(max_length = 30 ,verbose_name = '售后')
    group = models.ForeignKey(Group , on_delete = models.DO_NOTHING , verbose_name = '部门')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '售后单位'
        verbose_name_plural = '售后单位'

note/models/notes.py
from django.db import models
from django.contrib.auth.models import User , Group
from django.utils import timezone
from django.shortcuts import Http404
from .units import *
from .customers import *
from .report_times import *


#维修记录
class Note(models.Model):
    date = models.DateField(default = timezone.now)
    lb = models.ForeignKey(Unit_type , on_delete = models.DO_NOTHING ,
                           verbose_name = '类型')
    xh = models.ForeignKey(Unit_model , on_delete = models.DO_NOTHING ,
                            verbose_name = '型号')
    gz = models.CharField(max_length = 30 , verbose_name = '故障')
    jg = models.FloatField(verbose_name = '价格')
    sl = models.IntegerField(verbose_name = '数量')
    dd = models.CharField(max_length = 30 , verbose_name = '地点')
    bz = models.BooleanField(default = False , verbose_name = '报账')
    fs = models.CharField(max_length = 30 , verbose_name = '处理')
    sh = models.ForeignKey(Customer , on_delete = models.DO_NOTHING ,
                           verbose_name = '售后')
    zt = models.CharField(max_length = 15 , default = '未通知售后')
    tzsj = models.DateField(blank = True , null = True , verbose_name = '通知时间')
    dxsj = models.DateField(blank = True , null = True , verbose_name = '到校时间')
    fxsj = models.DateField(blank = True , null = True , verbose_name = '返校时间')
    xysc = models.DurationField(blank = True , null = True , verbose_name = '响应时长')
    xfsc = models.DurationField(blank = True , null = True , verbose_name = '修复时长')
    bzsj = models.ForeignKey(Report_time , on_delete = models.DO_NOTHING ,
                             blank = True , null = True , verbose_name = '报账时间')
    hj = models.FloatField(blank = True , null = True , verbose_name = '合计')
    owner = models.ForeignKey(User , on_delete = models.DO_NOTHING , verbose_name = '创建者')
    sn = models.CharField(max_length = 30,blank = True , null = True , default = '无' ,
                          verbose_name = '序列号')
    shry = models.CharField(max_length = 30,blank = True , null = True ,
                            verbose_name = '售后人员')
    shdh = models.CharField(max_length = 30,blank = True , null = True ,
                            verbose_name = '电话')

    def __str__(self):
        return self.lb.title

    def save(self):
        self.hj = self.jg * self.sl
        self.状态 = '未通知售后'
        if self.tzsj:self.zt = '已通知售后'   
        if self.dxsj:
            if not self.tzsj:
                raise Http404
            else:
                self.zt = '设备已返厂'
                self.xysc = self.dxsj - self.tzsj
        if self.fxsj:
            if not self.dxsj:
                raise Http404
            elif not self.scraped:
                self.状态 = '设备已修复'
                self.sfsc = self.fxsj - self.dxsj
            else:
                self.zt = '设备报废'
        super().save()
        

    class Meta:
        ordering = ['-date']
        verbose_name = '维修记录'
        verbose_name_plural = '维修记录'

note/views/edit.py
from django.shortcuts import render , redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from ..models import *
from ..forms import *
from .functions import edit_queryset

#删除记录
@login_required
def delete_note(request):
	user = request.user
	note_id = request.GET.get('note_id')
	note = Note.objects.get(id = note_id)
	if note.bzsj or user != note.owner:
		return render(request , 'note/404.html')
	else:
		note.delete()
		return redirect(reverse('manage_wbz'))

#修改记录
@login_required
def edit_note(request):
	user = request.user
	note_id = request.GET.get('note_id')
	if note_id:
		note = Note.objects.get(id = note_id)
		if request.method == 'POST':
			form = NoteForm(instance = note , data = request.POST)
			if form.is_valid():
				new_form = form.save(commit = False)
				if new_form.owner == user:
					new_form.save()
					return redirect(reverse('manage_wbz'))
				else:
					return render(request , 'note/404.html')
		else:
			form = NoteForm(instance = note)
			edit_queryset(user , form)
			context = {}
			context['form'] = form
			context['note_id'] = note_id
			return render(request , 'note/edit/edit_note.html' , context)
	else:
		return render(request , 'note/404.html')

#修改售后单位
@login_required
def edit_sh(request):
	owner = request.user
	groups = owner.groups.all()
	sh_id = request.GET.get('sh_id')
	if sh_id:
		sh = Customer.objects.get(id = sh_id)
		if request.method == 'POST':
			form = CustomerForm(instance = sh , data = request.POST)
			if form.is_valid():
				new_form = form.save(commit = False)
				if new_form.group in groups:
					new_form.save()
					return redirect(reverse('manage_sh'))
				else:
					return render(request , 'note/404.html')
		else:
			form = CustomerForm(instance = sh)
			form.fields['group'].queryset = groups
			context = {}
			context['form'] = form
			context['sh_id'] = sh_id
			return render(request , 'note/edit/edit_sh.html' , context)
	else:
		return render(request , 'note/404.html')

#修改设备类型
@login_required
def edit_lx(request):
	owner = request.user
	groups = owner.groups.all()
	lx_id = request.GET.get('lx_id')
	if lx_id:
		lx = Unit_type.objects.get(id = lx_id)
		if request.method == 'POST':
			form = Unit_typeForm(instance = lx , data = request.POST)
			if form.is_valid():
				new_form = form.save(commit = False)
				if new_form.sh.group in groups:
					new_form.save()
					return redirect(reverse('manage_lx'))
				else:
					return render(request , 'note/404.html')
		else:
			form = Unit_typeForm(instance = lx)
			if groups:
					for i in range(len(groups)):
						if i == 0:
							form.fields['sh'].queryset = Customer.objects.filter(group = groups[i])
						else:
							form.fields['sh'].queryset = form.fields['sh'].queryset.union(Customer.objects.filter(group = groups[i]))
			context = {}
			context['form'] = form
			context['lx_id'] = lx_id
			return render(request , 'note/edit/edit_lx.html' , context)
	else:
		return render(request , 'note/404.html')

#修改设备型号
@login_required
def edit_xh(request):
	owner = request.user
	groups = owner.groups.all()
	xh_id = request.GET.get('xh_id')
	if xh_id:
		xh = Unit_model.objects.get(id = xh_id)
		if request.method == 'POST':
			form = Unit_modelForm(instance = xh , data = request.POST)
			if form.is_valid():
				new_form = form.save(commit = False)
				if new_form.lx.sh.group in groups:
					new_form.save()
					return redirect(reverse('manage_xh'))
				else:
					return render(request , 'note/404.html')
		else:
			form = Unit_modelForm(instance = xh)
			if groups:
					for i in range(len(groups)):
						if i == 0:
							form.fields['lx'].queryset = Unit_type.objects.filter(sh__group = groups[i])
						else:
							form.fields['lx'].queryset = form.fields['lx'].queryset.union(Unit_type.objects.filter(sh__group = groups[i]))
			context = {}
			context['form'] = form
			context['xh_id'] = xh_id
			return render(request , 'note/edit/edit_xh.html' , context)
	else:
		return render(request , 'note/404.html')

note/views/functions.py
import datetime
from ..models import *
from ..forms import *
from django.contrib.auth.models import Group , User
from openpyxl import Workbook

#获取所有有报账权限的组
def get_info(user , groups):
	dict_permissions = {'电教部':user.permissions.bz_dj , '网络信息部':user.permissions.bz_wl , '计算机部':user.permissions.bz_jsj}
	list_groups = []
	for group in groups:
		if dict_permissions[group.name]:
			customers = Customer.objects.filter(group = group)
			list_groups.append(group)
	notes = Note.objects.filter(sh__group = list_groups[0] , bz = False)
	return list_groups , notes

#将时间格式装换成datetime.date类型
def str_to_date(date_str):
	list_date = date_str.split('-')
	date = datetime.date(int(list_date[0]) , int(list_date[1]) , int(list_date[2]))
	return date

#创建excel文件
def make_excel(notes_id , customer_id):
	group = Group.objects.get(customer__id = customer_id)
	filename = 'media/note/excel/%s.xlsx'%group.name
	wb = Workbook()
	ws = wb.active
	ws.append(['日期','类别','型号','价格','数量','总价','教室','售后'])
	for note_id in notes_id:
		note = Note.objects.get(id = note_id)
		ws.append([note.date , note.lb.title , note.xh.title , note.jg , note.sl , note.hj , note.dd , note.sh.title])
	wb.save(filename)
	return filename

#设置可访问表单
def edit_queryset(user , form):
	groups = user.groups.all()
	if groups:
		for i in range(len(groups)):
				if i == 0:
					form.fields['sh'].queryset = Customer.objects.filter(group = groups[i])
					form.fields['lb'].queryset = Unit_type.objects.filter(sh__group = groups[i])
					form.fields['xh'].queryset = Unit_model.objects.filter(lx__sh__group = groups[i])
				else:
					form.fields['sh'].queryset = form.fields['sh'].queryset.union(Customer.objects.filter(group = groups[i]))
					form.fields['lb'].queryset = form.fields['lb'].queryset.union(Unit_type.objects.filter(sh__group = groups[i]))
					form.fields['xh'].queryset = form.fields['xh'].queryset.union(Unit_model.objects.filter(lx__sh__group = groups[i]))
					

note/views/manage.py
from django.shortcuts import render , redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from ..models import *
from django.db.models import *

#未报账
@login_required
def manage_wbz(request):
	user = request.user
	notes = Note.objects.filter(bz = False , owner = user)
	total_p = notes.aggregate(total_p = Sum('hj'))['total_p']
	unit_types = Unit_type.objects.filter(note__owner = user , note__bz = False).annotate(ut_p = Sum('note__hj'))
	context = {}
	context['notes'] = notes
	context['total_p'] = total_p
	context['unit_types'] = unit_types
	return render(request , 'note/management/manage_wbz.html' , context)

#已报账
@login_required
def manage_ybz(request):
	user = request.user
	notes = Note.objects.filter(bz = True , owner = user)
	total_p = notes.aggregate(total_p = Sum('hj'))['total_p']
	unit_types = Unit_type.objects.filter(note__owner = user , note__bz = True).annotate(ut_p = Sum('note__hj'))
	context = {}
	context['notes'] = notes
	context['total_p'] = total_p
	context['unit_types'] = unit_types
	return render(request , 'note/management/manage_ybz.html' , context)

#售后
@login_required
def manage_sh(request):
	user = request.user
	groups = user.groups.all()
	customers = []
	for group in groups:
		customer = Customer.objects.filter(group = group)
		for c in customer:
			customers.append(c)
	context = {}
	context['notes'] = customers
	return render(request , 'note/management/manage_sh.html' , context)

#类型
@login_required
def manage_lx(request):
	user = request.user
	groups = user.groups.all()
	unit_types = []
	for group in groups:
		unit_type = Unit_type.objects.filter(sh__group = group)
		for u in unit_type:
			unit_types.append(u)
	context = {}
	context['notes'] = unit_types
	return render(request , 'note/management/manage_lx.html' , context)

#型号
@login_required
def manage_xh(request):
	user = request.user
	groups = user.groups.all()
	unit_models = []
	for group in groups:
		unit_model = Unit_model.objects.filter(lx__sh__group = group)
		for m in unit_model:
			unit_models.append(m)
	context = {}
	context['notes'] = unit_models
	return render(request , 'note/management/manage_xh.html' , context)

#密码
@login_required
def manage_mm(request):
	user = request.user
	if request.method == 'POST':
		psword = request.POST.get('password')
		user.set_password(psword)
		user.save()
		return redirect(reverse('login'))
	else:
		return render(request , 'note/management/manage_mm.html')

note/views/new_note.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from ..models import *
from ..forms import *
from .functions import edit_queryset

@login_required
def new_note(request):
	owner = request.user
	groups = owner.groups.all()
	if request.method == 'POST':
		form = NoteForm(request.POST)
		if form.is_valid():
			new_form = form.save(commit=False)
			new_form.owner = owner
			if new_form.sh.group in groups:
				new_form.save()
				return redirect(reverse('manage_wbz'))
			else:
				return render(request , 'note/404.html')
	else:
		form = NoteForm()
		edit_queryset(owner , form)
		context = {}
		context['form'] = form
		return render(request , 'note/new_note/new_note.html' , context)

def ajax_get_unit_types(request):
	customer_id = request.GET.get('customer_id')
	unit_types = Unit_type.objects.filter(sh__id = customer_id)
	context = {}
	context['unit_types'] = unit_types
	return render(request , 'note/new_note/ajax_get_unit_types.html' , context)

def ajax_get_unit_models(request):
	unit_type_id = request.GET.get('unit_type_id')
	unit_models = Unit_model.objects.filter(lx__id = unit_type_id)
	context = {}
	context['unit_models'] = unit_models
	return render(request , 'note/new_note/ajax_get_unit_models.html' , context)

@login_required
def new_customer(request):
	owner = request.user
	groups = owner.groups.all()
	if request.method == 'POST':
		form = CustomerForm(request.POST)
		if form.is_valid():
			new_form = form.save(commit = False)
			if new_form.group in groups:
				new_form.save()
				return redirect(reverse('new_note'))
			else:
				return render(request , 'note/404.html')
	else:
		form = CustomerForm()
		form.fields['group'].queryset = groups
		context = {}
		context['form'] = form
		return render(request , 'note/new_note/new_customer.html' , context)

@login_required
def new_unit_type(request):
	owner = request.user
	groups = owner.groups.all()
	if request.method == 'POST':
		form = Unit_typeForm(request.POST)
		if form.is_valid():
			new_form = form.save(commit = False)
			if new_form.sh.group in groups:
				new_form.save()
				return redirect(reverse('new_note'))
			else:
				return render(request , 'note/404.html')
	else:
		form = Unit_typeForm()
		if groups:
				for i in range(len(groups)):
					if i == 0:
						form.fields['sh'].queryset = Customer.objects.filter(group = groups[i])
					else:
						form.fields['sh'].queryset = form.fields['sh'].queryset.union(Customer.objects.filter(group = groups[i]))
		context = {}
		context['form'] = form
		return render(request , 'note/new_note/new_unit_type.html' , context)

@login_required
def new_unit_model(request):
	owner = request.user
	groups = owner.groups.all()
	if request.method == 'POST':
		form = Unit_modelForm(request.POST)
		if form.is_valid():
			new_form = form.save(commit = False)
			if new_form.lx.sh.group in groups:
				new_form.save()
				return redirect(reverse('new_note'))
			else:
				return render(request , 'note/404.html')
	else:
		form = Unit_modelForm()
		if groups:
				for i in range(len(groups)):
					if i == 0:
						form.fields['lx'].queryset = Unit_type.objects.filter(sh__group = groups[i])
					else:
						form.fields['lx'].queryset = form.fields['lx'].queryset.union(Unit_type.objects.filter(sh__group = groups[i]))
		context = {}
		context['form'] = form
		return render(request , 'note/new_note/new_unit_model.html' , context)

templates/note/report/ajax_get_notes.html
{%for note in notes%}
                <tr>
                  <td><input type="checkbox" name="ckb" value="{{note.id}}" checked></td>
                  <td>{{note.date}}</td>
                  <td>{{note.lb}}</td>
                  <td>{{note.xh}}</td>
                  <td>{{note.gz}}</td>
                  <td>{{note.jg}}</td>
                  <td>{{note.sl}}</td>
                  <td>{{note.dd}}</td>
                  <td>{{note.fs}}</td>
                  <td>{{note.zt}}</td>
                  <td>{{note.hj}}</td>
                  <td>
                    <button class="btn btn-link btn-xs show_detail" type="button" data-toggle="modal" data-target="#modal_detail" value="{{note.id}}">详细</button>
                  </td>
                </tr>
                {%empty%}
                没有记录
                {%endfor%}

templates/note/report/bz.html
{%extends 'note/base.html'%}
{%load staticfiles%}
{%block head%}
<link rel="stylesheet" href="{%static 'note/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css'%}">
<link rel="stylesheet" href="{%static 'note/my_css/table_width.css'%}">
{%endblock%}
{%block navbar%}
<li class="active bz_navbar"><a href="{%url 'bz'%}">报账</a></li>
{%endblock%}
{%block left_navbar_header%}
售后单位
{%endblock%}
{%block left_navbar%}
    {%for g in list_groups%}
    {%if forloop.first%}
      <li class="active treeview menu-open">
          <a href="#"><i class="fa fa-link"></i> <span class="forname" value="{{g.name}}">{{g.name}}</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            {%for c in g.customer_set.all%}
            {%if forloop.first%}
            <li class="active forchoice" value="{{c.id}}"><a href="#">{{c.title}}</a></li>
            {%else%}
            <li class="forchoice" value="{{c.id}}"><a href="#">{{c.title}}</a></li>
            {%endif%}
            {%endfor%}
          </ul>
        </li>
      {%else%}
      <li class=" treeview">
          <a href="#"><i class="fa fa-link"></i> <span class="forname" value="{{g.name}}">{{g.name}}</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            {%for c in g.customer_set.all%}
            <li class="forchoice" value="{{c.id}}"><a href="#">{{c.title}}</a></li>
            {%endfor%}
          </ul>
        </li>
      {%endif%}
      {%endfor%}
{%endblock%}
{%block content-header-1%}
报账
{%endblock%}
{%block content-header-1-content%}
某部门
{%endblock%}
{%block content-header%}
首页
{%endblock%}
{%block content-header-2%}
报账
{%endblock%}
{%block content-header-2-content%}
某部门
{%endblock%}
{%block content%}
<form class="form-horizontal" action="{%url 'bz'%}" method="post">
  {%csrf_token%}
  <div class="row">
    <div class="col-xs-6">
      <div class="form-group">  
                  <div class="box-body">      
                    <label for="id_title" class="col-sm-2 control-label">名称</label>
                    <div class="col-sm-10"><input type="text" name="title" class="form-control" id="id_title"></div>              
              </div>
            </div>
    </div>
    <div class="col-xs-6">
      <div class="form-group"> 
      <div class="box-body">        
                    <label for="id_date" class="col-sm-2 control-label">日期</label>
                    <div class="col-sm-10"><input type="date" name="date" class="form-control" id="id_date"></div>              
              </div>
              </div>
    </div>
    <input type="text" name="sh" hidden id='id_sh'>    
  </div>
<div class="row">
        <div class="col-xs-12">
          <!-- 数据表格 -->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">统计信息</h3>
            </div>
            <div class="box-body">
              <div class="table-responsive">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>选择</th>
                  <th>日期</th>
                  <th>类型</th>
                  <th>型号</th>
                  <th>故障</th>
                  <th>单价</th>
                  <th>数量</th>
                  <th>地点</th>
                  <th>处理</th>
                  <th>状态</th>
                  <th>合计</th>
                  <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {%for note in notes%}
                <tr>
                  <td><input type="checkbox" name="ckb" value="{{note.id}}" checked></td>
                  <td>{{note.date}}</td>
                  <td>{{note.lb}}</td>
                  <td>{{note.xh}}</td>
                  <td>{{note.gz}}</td>
                  <td>{{note.jg}}</td>
                  <td>{{note.sl}}</td>
                  <td>{{note.dd}}</td>
                  <td>{{note.fs}}</td>
                  <td>{{note.zt}}</td>
                  <td>{{note.hj}}</td>
                  <td>
                    <button class="btn btn-link btn-xs show_detail" type="button" data-toggle="modal" data-target="#modal_detail" value="{{note.id}}">详细</button>
                  </td>
                </tr>
                {%endfor%}
                </tbody>
              </table>
              </div>
              <div class="btn-group pull-right">
                <button class="btn btn-info" formaction="{%url 'dy'%}">打印页面</button>
                <button class="btn btn-info" formaction="{%url 'download'%}">下载excel</button>
                <button class="btn btn-info" onclick="return report_waring()">报账</button>
            </div>
          </div>
        </div>     
      </div>
      </div>
</form>
<!-- 模态框 -->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="modal_detail">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
{%endblock%}
{%block script%}
<script src="{%static 'note/bower_components/datatables.net/js/jquery.dataTables.min.js'%}"></script>
<script src="{%static 'note/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js'%}"></script>
<script src="{%static 'note/my_js/report.js'%}"></script>
{%endblock%}

templates/note/report/dy.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="widtd=device-widtd, initial-scale=1">
    <link rel="stylesheet" href="{%static 'note/bower_components/bootstrap/dist/css/bootstrap.min.css'%}">
    <title>设备管理系统</title>
	<style>
		td{
			border:1px solid #000!important
}
	tr{
			border:1px solid #000
}
	</style>
  </head>
  <body>
    <table class = 'table'>
	<tr><td colspan = 8 align = 'center'>维修汇总</td></tr>
	 <tr   align = 'center'><td>序号</td><td>日期</td><td>类别</td><td>型号</td><td>单价（元）</td><td>数量（台）</td><td>备注（教室编号）</td><td>合计（元）</td></tr>
        {% for content in notes %}
	<tr  align = 'center'><td>{{forloop.counter}}</td><td>{{content.date|date:"Y.m.d"}}</td><td>{{content.lb}}</td><td>{{content.xh}}</td><td>{{content.jg}}</td><td>{{content.sl}}</td><td>{{content.dd}}</td><td>{{content.hj}}</td></tr>
	{% endfor %}
   <tr><td colspan = 8 >总计（元）：{{total_price}}</td></tr>
    </table>
  </body>
</html>