ems/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('note.urls')),
    path('login' , login , name = 'login'),
    path('logout' , logout_view , name = 'logout'),
    path('ckeditor' , include('ckeditor_uploader.urls')),
    path('items' , include('items.urls')),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import *

urlpatterns = [
		path('' , show_items , name = 'show_items'),
		path('ajax_process' , ajax_process , name = 'ajax_process'),
]

items/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Item(models.Model):
	title = models.CharField(max_length = 50 , verbose_name = '项目名称')

class Item_process(models.Model):
	item = models.ForeignKey(Item ,verbose_name = '所属项目' , on_delete = models.DO_NOTHING)
	title = models.CharField(max_length = 50 , verbose_name = '名称')
	text = RichTextUploadingField(verbose_name = '内容')

items/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def show_items(request):
	item = Item.objects.first()
	context = {}
	context['item'] = item
	return render(request , 'items/show_items.html' , context)

def ajax_process(request):
	process_id = request.GET.get('process_id')
	process = Item_process.objects.get(id = process_id)
	context = {}
	context['process'] = process
	return render(request , 'items/ajax_process.html' , context)

templates/items/ajax_process.html
            <div class="box-header with-border">
              <h3 class="box-title">{{process.title}}</h3>
            </div>
            <div class="box-body">
            	<p>{{process.text|safe}}</p>
            </div>

templates/items/base.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>设备管理系统</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{%static 'note/bower_components/bootstrap/dist/css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{%static 'note/bower_components/font-awesome/css/font-awesome.min.css'%}">
  <link rel="stylesheet" href="{%static 'note/bower_components/Ionicons/css/ionicons.min.css'%}">
  <link rel="stylesheet" href="{%static 'note/dist/css/AdminLTE.min.css'%}">
  <link rel="stylesheet" href="{%static 'note/dist/css/skins/_all-skins.min.css'%}">
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  {%block head%}{%endblock%}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
	<!-- 上方导航栏 -->
  <header class="main-header">
  	<!-- logo部分 -->
    <a href="{%url 'wbz_all'%}" class="logo">
    	<!-- 折叠时 -->
      <span class="logo-mini">EMS</span>
      <!-- 展开时 -->
      <span class="logo-lg">设备管理系统</span>
    </a>

    <!-- 导航部分 -->
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- 小屏幕折叠部分 -->
       <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- 导航栏内容 -->
          <li><a href="{%url 'show_items'%}">所有项目</a></li>
        	{%block navbar%}{%endblock%}
        </ul>
      </div>
    </nav>
  </header>
  <!-- 左边导航栏 -->
  <aside class="main-sidebar">
    <section class="sidebar">
      <!-- 用户信息 -->
       {%if request.user.is_authenticated%}
      <div class="user-panel">
        <div class="pull-left image">
          <img src="media/note/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{request.user.first_name}}</p>
          <span><i class="fa fa-circle text-success"></i> 在线</span>
        </div>
      </div>
      {%else%}
      <div class="user-panel">
        <div class="pull-left image">
          <img src="media/note/img/avatar5.png" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>你好，朋友</p>
          <span> 欢迎参观</span>
        </div>
      </div>
      {%endif%}
      <!-- 左边导航部分 -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">{%block left_navbar_header%}{%endblock%}</li>
        <!-- 选项 -->
        {%block left_navbar%}{%endblock%}
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- 内容区域 -->
  <div class="content-wrapper">
    <!-- 具体内容 -->
    <section class="content container-fluid">
      {%block content%}{%endblock%}
    </section>
  </div>
    <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>作者:</b> wx
    </div>
    <strong>Copyright &copy; <a href="http://www.tcsisu.com/net/">现代教育技术中心</a></strong>
  </footer>
</div>
	<!-- script区域 -->
<script src="{%static 'note/bower_components/jquery/dist/jquery.min.js'%}"></script>
<script src="{%static 'note/bower_components/bootstrap/dist/js/bootstrap.min.js'%}"></script>
<script src="{%static 'note/dist/js/adminlte.min.js'%}"></script>
{%block script%}{%endblock%}
</body>
</html>

templates/items/show_items.html
{%extends 'items/base.html'%}
{%block left_navbar_header%}
内容
{%endblock%}
{%block left_navbar%}
{%for ip in item.item_process_set.all%}
<li class="ajax_process" value="{{ip.id}}"><a href="#" ><i class="fa fa-table"></i> <span>{{ip.title}}</span></a></li>
{%endfor%}
{%endblock%}
{%block content%}
<div class="row">
	<div class="col-md-10 col-md-offset-1 col-xs-12">
		<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">{{item.item_process_set.first.title}}</h3>
            </div>
            <div class="box-body">
            	<p>{{item.item_process_set.first.text|safe}}</p>
            </div>
          </div>
	</div>
</div>
{%endblock%}
{%block script%}
<script type="text/javascript">
	$(".ajax_process").click(function(){
		var process_id = $(this).val()
		$.ajax({
			url:"{%url 'ajax_process'%}",
			data:{'process_id':process_id},
			success:function(data){
				$(".box-primary").html(data)
			}
		})
	})
</script>
{%endblock%}